name: Deploy to heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: heroku login
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: city--inspector
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
